name: lumo
description: Lumo — IM platform Flutter client (iOS / Android / Web / Desktop)
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  http_parser: ^4.0.2
  web_socket_channel: ^2.4.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.4.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
